<?php

namespace MobinDev\Novin_Commerce\Common\Accounting\WebPrd;

use MobinDev\Novin_Commerce\Common\Text_Encoding;

/**
 * Single boundary for accounting WebPrd data.
 *
 * WebPrd is an external contract, not a WordPress data structure. This class
 * validates and exposes only explicitly named fields so modules cannot make
 * incompatible assumptions while independently decoding the JSON blob.
 */
final class WebPrd_Parser {

	const MAX_BYTES = 500000;

	/** @var array<string,mixed> */
	private $data = array();
	/** @var bool */
	private $valid = false;
	/** @var string */
	private $error = '';
	/** @var string */
	private $hash = '';

	/**
	 * @param mixed $raw JSON string or an already-decoded associative array.
	 */
	public function __construct( $raw ) {
		if ( is_array( $raw ) ) {
			$this->data  = $raw;
			$this->valid = true;
			$this->hash  = md5( (string) wp_json_encode( $raw ) );
			return;
		}

		if ( ! is_string( $raw ) || '' === trim( $raw ) ) {
			$this->error = 'source_missing';
			return;
		}
		if ( strlen( $raw ) > self::MAX_BYTES ) {
			$this->error = 'source_too_large';
			return;
		}

		$normalized = Text_Encoding::normalize( $raw );
		$decoded    = json_decode( $normalized, true, 32 );
		if ( JSON_ERROR_NONE !== json_last_error() || ! is_array( $decoded ) ) {
			$this->error = 'invalid_json';
			return;
		}

		$this->data  = $decoded;
		$this->valid = true;
		$this->hash  = md5( $normalized );
	}

	/**
	 * @param mixed $raw
	 * @return self
	 */
	public static function from( $raw ) {
		return new self( $raw );
	}

	public function is_valid() {
		return $this->valid;
	}

	public function error_code() {
		return $this->error;
	}

	public function hash() {
		return $this->hash;
	}

	/**
	 * Read a top-level field only. Nested business semantics belong in the
	 * explicit methods below; callers should not use this as a second parser.
	 *
	 * @param string $key
	 * @param mixed  $default
	 * @return mixed
	 */
	public function field( $key, $default = null ) {
		return array_key_exists( $key, $this->data ) ? $this->data[ $key ] : $default;
	}

	/**
	 * @return array<string,mixed>
	 */
	public function identity() {
		return array(
			'guid'       => $this->text_field( 'Guid' ),
			'id'         => $this->scalar_text( 'Id' ),
			'id_product' => $this->scalar_text( 'IdProduct' ),
			'code'       => $this->text_field( 'Code' ),
			'sku'        => $this->text_field( 'Sku' ),
			'slug'       => $this->text_field( 'Slug' ),
		);
	}

	/**
	 * @return array<string,mixed>
	 */
	public function catalog() {
		return array(
			'name'       => $this->text_field( 'Name' ),
			'group_name' => $this->text_field( 'GroupName' ),
			'guid_group' => $this->text_field( 'GuidGroup' ),
			'guid_unit'  => $this->text_field( 'GuidVahed' ),
			'unit_name'  => $this->text_field( 'VahedName' ),
			'kind'       => $this->numeric_field( 'Kind' ),
		);
	}

	/**
	 * Accounting price levels are explicit Sell1..Sell8 fields. They are not
	 * WordPress roles and are never generated by array position.
	 *
	 * @return array<int,array{level:int,field:string,value:mixed,valid:bool}>
	 */
	public function price_levels() {
		$levels = array();
		for ( $i = 1; $i <= 8; $i++ ) {
			$field = 'Sell' . $i;
			$value = $this->field( $field, null );
			$valid = $this->valid_price( $value );
			$levels[] = array(
				'level'  => $i,
				'field'  => $field,
				'value'  => $valid ? (string) $value : null,
				'valid'  => $valid,
			);
		}
		return $levels;
	}

	/**
	 * Return PriceRoleList entries without assigning roles by array order.
	 *
	 * @return array<int,array<string,mixed>>
	 */
	public function price_role_list() {
		$value = $this->field( 'PriceRoleList', array() );
		if ( is_string( $value ) ) {
			$value = $this->decode_embedded_array( $value );
		}
		if ( ! is_array( $value ) ) {
			return array();
		}

		// Some legacy payloads contain one named entry rather than a list. It
		// is safe to wrap that entry; a role=>price map is deliberately not
		// interpreted because it has no explicit accounting entry contract.
		$named_keys = array( 'WordPressRoleName', 'RoleName', 'Role', 'role', 'Price', 'price', 'RegularPrice', 'SalePrice', 'salePrice' );
		if ( array_intersect( $named_keys, array_keys( $value ) ) ) {
			return array( $value );
		}
		return array_values( $value );
	}

	/**
	 * PriceRoleList has existed as an array, JSON string and PHP-serialized
	 * string. Decode only this nested boundary, with classes disabled for
	 * serialized input; no caller is allowed to invent a positional mapping.
	 *
	 * @param string $value
	 * @return array
	 */
	private function decode_embedded_array( $value ) {
		$value = trim( Text_Encoding::normalize( $value ) );
		if ( '' === $value ) {
			return array();
		}
		$decoded = json_decode( $value, true, 32 );
		if ( JSON_ERROR_NONE === json_last_error() && is_array( $decoded ) ) {
			return $decoded;
		}
		$decoded = @unserialize( $value, array( 'allowed_classes' => false ) ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- malformed legacy payloads must fail closed.
		return is_array( $decoded ) ? $decoded : array();
	}

	/**
	 * Prices[] is an explicit source field and is kept separate from Sell1..8.
	 *
	 * @return array<int,mixed>
	 */
	public function prices() {
		$value = $this->field( 'Prices', array() );
		return is_array( $value ) ? array_values( $value ) : array();
	}

	public function pricing() {
		return array(
			'levels'          => $this->price_levels(),
			'price_role_list' => $this->price_role_list(),
			'prices'          => $this->prices(),
		);
	}

	/**
	 * Normalize the explicit PriceRoleList contract once. No role is assigned
	 * by position; an entry without a named role or valid price is retained as
	 * an invalid domain record for health diagnostics.
	 *
	 * @return array<int,array{name:string,price:float|null,sale_price:float|null}>
	 */
	public function role_prices() {
		$result = array();
		foreach ( $this->price_role_list() as $entry ) {
			if ( ! is_array( $entry ) ) continue;
			$name = '';
			foreach ( array( 'WordPressRoleName', 'RoleName', 'Role', 'role' ) as $key ) {
				if ( isset( $entry[ $key ] ) && is_scalar( $entry[ $key ] ) && '' !== trim( (string) $entry[ $key ] ) ) { $name = trim( Text_Encoding::normalize( $entry[ $key ] ) ); break; }
			}
			$price = null;
			foreach ( array( 'Price', 'price', 'RegularPrice', 'Value', 'value' ) as $key ) {
				if ( array_key_exists( $key, $entry ) && is_numeric( $entry[ $key ] ) && (float) $entry[ $key ] > 0 ) { $price = (float) $entry[ $key ]; break; }
			}
			$sale_price = null;
			foreach ( array( 'SalePrice', 'salePrice', 'Sale', 'sale' ) as $key ) {
				if ( array_key_exists( $key, $entry ) && is_numeric( $entry[ $key ] ) && (float) $entry[ $key ] > 0 ) { $sale_price = (float) $entry[ $key ]; break; }
			}
			$result[] = array( 'name' => $name, 'price' => $price, 'sale_price' => $sale_price );
		}
		return $result;
	}

	public function discount() {
		return array(
			'percent'    => $this->numeric_field( 'DiscountPercent' ),
			'start_date' => $this->text_field( 'DiscountStartDate' ),
			'end_date'   => $this->text_field( 'DiscountEndDate' ),
		);
	}

	/**
	 * Inventory deliberately keeps Mojodi separate from warehouse totals.
	 * Invalid/missing Amount values are represented as null, never coerced to
	 * zero. Warehouse scope is resolved by Inventory_Health_Service.
	 */
	public function inventory() {
		$relations = $this->field( 'PrdAnbarRelation', array() );
		$rows      = array();
		if ( is_array( $relations ) ) {
			foreach ( $relations as $relation ) {
				if ( ! is_array( $relation ) ) {
					continue;
				}
				$amount = array_key_exists( 'Amount', $relation ) && is_numeric( $relation['Amount'] )
					? (float) $relation['Amount']
					: null;
				if ( null !== $amount && $amount < 0 ) {
					$amount = null;
				}
				$rows[] = array(
					'product_guid'   => $this->text_value( $relation, 'PrdGuid' ),
					'warehouse_guid' => $this->text_value( $relation, 'AnbarGuid' ),
					'amount'         => $amount,
				);
			}
		}

		$valid_rows = array_values(
			array_filter(
			$rows,
			static function ( $row ) {
				return null !== $row['amount'] && '' !== $row['warehouse_guid'];
			}
		)
		);
		return array(
			'source_mojodi'       => $this->numeric_field( 'Mojodi' ),
			'warehouse_relations' => $rows,
			'valid_relations'     => $valid_rows,
			'warehouse_count_all' => count( $valid_rows ),
			'warehouse_total_all' => array_sum( array_column( $valid_rows, 'amount' ) ),
		);
	}

	public function units() {
		return array(
			'base_name' => $this->text_field( 'VahedName' ),
			'v2_qty'    => $this->positive_number_field( 'V2Qt' ),
			'v3_qty'    => $this->positive_number_field( 'V3Qt' ),
			'v2_guid'   => $this->text_field( 'V2Guid' ),
			'v3_guid'   => $this->text_field( 'V3Guid' ),
		);
	}

	public function attributes() {
		return array(
			'product_attribute_guids' => $this->list_field( 'ProductAttributeGuids' ),
			'attribute_relations'     => $this->list_field( 'AttributeRelations' ),
			'related_attributes'      => $this->list_field( 'RelatedAttributes' ),
		);
	}

	public function media() {
		return array(
			'files'            => $this->list_field( 'Files' ),
			'image_list_data'  => $this->list_field( 'ImageListData' ),
			'other_pics'       => $this->list_field( 'OtherPics' ),
			'pic'              => $this->field( 'Pic', null ),
		);
	}

	public function technical() {
		$values = array();
		for ( $i = 1; $i <= 8; $i++ ) {
			$values[ 'T' . $i ] = $this->field( 'T' . $i, null );
		}
		$values['list'] = $this->list_field( 'PrdTechnicalList' );
		return $values;
	}

	public function synchronization() {
		return array(
			'modified'          => $this->field( 'Modified', null ),
			'version'           => $this->scalar_text( 'Version' ),
			'client_version'    => $this->scalar_text( 'ClientVersion' ),
			'server_status'     => $this->text_field( 'ServerStatus' ),
			'send_to_server'    => $this->field( 'SendToServerDate', null ),
		);
	}

	public function production() {
		return array(
			'kind'               => $this->numeric_field( 'Kind' ),
			'production_capacity'=> $this->numeric_field( 'ProductionCapacity' ),
			'formula_guid'       => $this->text_field( 'TolidFormulaGuid' ),
		);
	}

	public function seo() {
		return array(
			'title'        => $this->text_field( 'SeoTitle' ),
			'description'  => $this->text_field( 'SeoDescription' ),
			'focus_keyword' => $this->text_field( 'SeoFocusKeyword' ),
			'keywords'     => $this->list_field( 'Keywords' ),
			'meta_desc'    => $this->text_field( 'MetaDesc' ),
		);
	}

	private function text_field( $key ) {
		return $this->scalar_text( $key );
	}

	private function scalar_text( $key ) {
		$value = $this->field( $key, '' );
		return is_scalar( $value ) ? trim( Text_Encoding::normalize( $value ) ) : '';
	}

	private function text_value( array $row, $key ) {
		$value = isset( $row[ $key ] ) ? $row[ $key ] : '';
		return is_scalar( $value ) ? trim( Text_Encoding::normalize( $value ) ) : '';
	}

	private function numeric_field( $key ) {
		$value = $this->field( $key, null );
		return is_numeric( $value ) ? (float) $value : null;
	}

	private function positive_number_field( $key ) {
		$value = $this->numeric_field( $key );
		return null !== $value && $value > 0 ? $value : null;
	}

	private function valid_price( $value ) {
		return is_numeric( $value ) && is_finite( (float) $value ) && (float) $value > 0;
	}

	private function list_field( $key ) {
		$value = $this->field( $key, array() );
		return is_array( $value ) ? array_values( $value ) : array();
	}
}
